### PR TITLE
l10n(zh-Hant): Update translation for 2.0.2

### PR DESCRIPTION
**Pull request by pan93412**
This PR completes the translation of zh-Hant (100%), unifies the terms (such as '拷貝'), and reviews the current translation.

r? @itszero @toto6038 [done]

### CODE REVIEW

**Review by itszero — APPROVED** [review]
lgtm!

**Comment by MattKiazyk** [comment]
@pan93412 with one Localizable file now conflicts happen all the time. Can you rebase and I'll get that merged in. Thanks

**Comment by pan93412** [comment]
Sure. Hold on.

**Comment by pan93412** [comment]
> @pan93412 with one Localizable file now conflicts happen all the time. Can you rebase and I'll get that merged in. Thanks

Done. Besides, I make a tool that makes the merge easier, you can take a look at https://github.com/pan93412/string-catalog-merger :)

**Comment by pan93412** [comment]
How about this? cc @MattKiazyk

**Comment by MattKiazyk** [comment]
Thanks!

**Pull request merged**
