### PR TITLE
chore: lossless png compression

### PR DESCRIPTION
**Pull request by mikeirvingweb**
Lossless PNG image compression

smaller downloads, smaller repo, smaller app size

### CODE REVIEW

**Comment by chickdan** [comment]
It's subtle but the colors of both the Robots & Pencils logo as well as the app icon are muted after being compressed.

**Comment by mikeirvingweb** [comment]
I think that's due to an opacity thing.. obvious on the app icon.

I will make a further commit at some point, rolling back those two

**Comment by mikeirvingweb** [comment]
@chickdan I have rolled back the app icons, including icon.png in the root, and the beta app icon, and the R&P graphic.

so there's much less in the PR now, but hopefully what is left is fine.

**Comment by MattKiazyk** [comment]
👍

**Pull request merged**
