### PR TITLE
SDK column in the info panel supports displaying visionOS

### PR DESCRIPTION
**Pull request by LavareX**
Xcode 15 beta 2 now supports visionOS SDK.

### CODE REVIEW

**Comment by calimarkus** [comment]
Should be good to merge it?

**Comment by calimarkus** [comment]
This would resolve issue https://github.com/XcodesOrg/XcodesApp/issues/432

**Review by MattKiazyk — APPROVED** [review]
Thanks @LavareX 

Sorry for the late response.

**Comment by Saafo** [comment]
Xcode 15.2 came with support of visionOS 1.0, should we release a new version to support this feature?

**Pull request merged**
